services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app  # Если нужно менять код без пересборки

  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # Проверяет, что БД готова
      test: ["CMD-SHELL", "pg_isready -U user -d visits"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: